### ISSUE TITLE
Consider upgrading PHP version requirement?

### ISSUE THREAD

**Issue by rexxars** [imbo/imboclient-php#103]
I think we should consider requiring PHP >= 5.5 for future versions of the client. If we make the next release of the client compatible with PHP 5.3 + Imbo 2.0, I think we can start working on a 2.0 of the client which requires a more recent PHP version.

Mainly I'm interested in using some more modern dependencies such as the latest Guzzle and Behat, but it would also be nice to be able to use short array syntax, for instance.

**Comment by rexxars** [comment]
Considering end of life for PHP 5.4 has been reached, I think it makes sense to move to PHP 5.5 as the minimum required version from the next version. See http://php.net/supported-versions.php for more details on end of life for PHP versions.

**Comment by peter279k** [comment]
This issue is related to issue #113.

**Comment by christeredvartsen** [comment]
Both Imbo-3.0 and other related packages written in PHP will require PHP >= 7.2 (https://github.com/imbo/imbo/issues/605).
