### ISSUE TITLE
Allow specifying the user when calling ImboClient:getImageUrl

### ISSUE THREAD

**Issue by aptomaKetil** [imbo/imboclient-php#111]
We're receiving image URLs from multiple sources and need to retain the user from the original URL.

We could solve this ourselves by using `getUser`/`setUser` to create a backup of the originally configured user, replace it with the user from the URL, generate the image, then restore the original user. This feels like a hack, though.

Would it be possible to add an (optional) second parameter to `getImageUrl` which would allow us to override the configured user on a case-by-case basis?

I'd be happy to provide a PR for this.

**Comment by matslindh** [comment]
Earlier we kind of decided that "use multiple ImboClients if you have this issue often", but I can see how it would be useful as a "one-off" thing to avoid creating more clients for just a single resource.

I would however like to have it as a method on the `ImageURL` instead, to avoid introducing a magic value on `getImageURL`. Could we do `overrideUser("foo")` on the ImageURL returned instead? That would keep the state change internally in `ImageURL`. A possible issue is that we have many URL classes to represent different endpoints, and you could argue that we would need the same support for all the classes - but ImageURL is probably special in this manner.

The other option is to have multiple ImboClients (it should be lightweight enough to not introduce much overhead), and just pick the one you want in your template layer (i.e. `$clients["foo"]->getImageURL()` or `$clients->get("foo")->getImageURL()` from a small container object).

I'm +0 on the change to `ImageUrl` class.

**Comment by christeredvartsen** [comment]
I'm not a fan of introducing a `$user` parameter in the `getImageUrl` method of a client instance that has been configured to work for a specific user. I'm more in favor of introducing something like @matslindh specifies, for instance an `overrideUser` method of sorts.

**Comment by aptomaKetil** [comment]
Alright, I can provide a PR for an `overrideUser` on `ImageUrl`.

**Comment by aptomaKetil** [comment]
Closing after discussion with @christeredvartsen. We'll replace the user in our own logic for the time being.

**Comment by christeredvartsen** [comment]
For future reference, a possible solution is something like the snippet found in the docs regarding translating old URL's: http://imboclient-php.readthedocs.org/en/2.0.3/#translating-old-urls
