### ISSUE TITLE
Update guzzle to newest version

### ISSUE THREAD

**Issue by M4R7iNP** [imbo/imboclient-php#113]
Right now [guzzle is pinned at 3.8](https://github.com/imbo/imboclient-php/blob/41287eb61bf11054822468dd6cc2cdf0e220e115/composer.json#L22), but there is a [far newer version of guzzle avaiable](https://packagist.org/packages/guzzlehttp/guzzle).

**Comment by peter279k** [comment]
If we use the latest stable `Guzzle` version, we also consider dropping old PHP versions.

As far as I know, the latest `Guzzle` version requires `php-5.5` at least.

**Comment by christeredvartsen** [comment]
I am currently working on Imbo-3.0, and will also update client libs.
