### ISSUE TITLE
Metadata query

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imboclient-php#94]
Work has been started with the support of metadata queries in the server. The client must be able to support this as well.

**Comment by rexxars** [comment]
We decided not to include metadata search as a core part of Imbo, but rather implement it as [an event listener](https://github.com/imbo/imbo-metadata-search). The client should thus have no functions for doing metadata queries - instead this should be handled by an extension of the client or a plugin of some sort. Closing this.
